fixed symfony process
BRACKETS-by-TRIAD/craftable-installer pull request #10
Opened 2019-12-06 09:53 UTC by RichardDominik

2019-12-06 10:01 UTC, RichardDominik commented
https://github.com/BRACKETS-by-TRIAD/code-style-fixer/commit/90404f03fe1fcfbe7abf820bfced00fa339589e7

2019-12-06 10:05 UTC, palypster commented
@dejwCake it looks like you already encountered this problem in code-style-fixer package. So basically we need to do the same in this package, as well. Correct?

2019-12-09 16:10 UTC, dejwCake requested changes

2019-12-09 16:10 UTC, dejwCake commented on src/NewCommand.php
> +        $process = Process::fromShellCommandline(implode(' && ', $commands), null, null, null, null);
Why the solution is not the same as for code style fixer? I guess also here you could have older symfony installed, so we have to check for the method existence.

2019-12-09 16:21 UTC, dejwCake approved these changes

2019-12-09 16:24 UTC, merged